Add case sensitivity in search and replace tool.
mlorenzano/linguist pull request #32
Opened 2020-03-29 17:40 UTC by fede-basseni

I added case-sensitivity checkbox in search and replace tool.

2020-03-29 20:01 UTC, guerinoni requested changes

2020-03-29 20:01 UTC, guerinoni commented on src/src/language.cpp
> +                            (caseSensitivity) ? Qt::CaseSensitive : Qt::CaseInsensitive);
remove parenthesis

2020-03-29 20:01 UTC, guerinoni commented on src/src/mainwindow.cpp
> +    sLabel->setText("Search:");
make string translatable

2020-03-29 20:01 UTC, guerinoni commented on src/src/mainwindow.cpp
> +    rLabel->setText("Replace with:");
make string translatable

2020-03-29 20:01 UTC, guerinoni commented on src/src/mainwindow.cpp
> +    caseSensitiveOption->setText("Case sentive");
make string translatable

2020-04-02 15:56 UTC, guerinoni commented on src/src/language.cpp
> +                            caseSensitivity ? Qt::CaseSensitive : Qt::CaseInsensitive);
wrong indentation

2020-04-02 15:59 UTC, guerinoni commented
I tried this with a string "lol" and "LOL", replacing "lol" with case sensitive flag changes all item

2020-04-02 16:18 UTC, fede-basseni commented
> I tried this with a string "lol" and "LOL", replacing "lol" with case sensitive flag changes all item

I retried the function with case sensitive but I didn't see any problems. 
It's working correctly.

2020-04-03 06:01 UTC, guerinoni commented
> > I tried this with a string "lol" and "LOL", replacing "lol" with case sensitive flag changes all item
> 
> I retried the function with case sensitive but I didn't see any problems.
> It's working correctly.

it works, but there are some issues editing a value in the table... because of this I reported some issues on this feature

2020-04-03 06:02 UTC, guerinoni approved these changes

2020-04-03 09:48 UTC, AndreaRicchi approved these changes
LGTM!

2020-04-03 10:10 UTC, merged